---
- name: Verify that required DNS zone attributes are defined
  ansible.builtin.assert:
    that:
      - "{{ item }} is defined"
      - "{{ item }} != None"
    fail_msg: "{{ item }} needs to be set for the role to work"
    success_msg: "Required variable {{ item }} is defined"
  changed_when: false
  diff: false
  loop:
    - nsd_zone_vars.name
    - nsd_zone_vars.ttl
    - nsd_zone_vars.dns_refresh
    - nsd_zone_vars.dns_retry
    - nsd_zone_vars.dns_expire
    - nsd_zone_vars.dns_negative_response_cache

- name: Set zone name variable and construct zone_records variable name
  ansible.builtin.set_fact:
    nsd_zone_name: "{{ nsd_zone_vars.name }}"
    nsd_zone_records_name: "{{ 'nsd_' + nsd_zone_vars.name | replace('.', '_') + '_records' }}"

- name: Verify that required zone records are defined
  ansible.builtin.assert:
    that:
      - "{{ lookup('ansible.builtin.vars', 'nsd_zone_records_name', default='') }} | list is defined"
      - "{{ lookup('ansible.builtin.vars', 'nsd_zone_records_name', default='') }} | list |  length > 0"
      - "{{ lookup('ansible.builtin.vars', 'nsd_zone_records_name', default='') }} | list != None"
    fail_msg: "{{ nsd_zone_records_name }} needs to be set for the role to work"
    success_msg: "Required variable {{ nsd_zone_records_name }} is defined"
  changed_when: false
  diff: false

- name: Verify that required DKIM attributes are defined
  ansible.builtin.assert:
    that:
      - "{{ item }} is defined"
      - "{{ item }} | length > 0"
      - "{{ item }} != None"
    fail_msg: "{{ item }} needs to be set for the role to work"
    success_msg: "Required variable {{ item }} is defined"
  changed_when: false
  diff: false
  loop:
    - nsd_zone_vars.dkim_domain
    - nsd_zone_vars.dkim_keys
  when: nsd_zone_vars.dkim_enabled is sameas true

- name: Verify that required reverse zone attributes are defined
  ansible.builtin.assert:
    that:
      - "{{ item }} is defined"
      - "{{ item }} | length > 0"
      - "{{ item }} != None"
    fail_msg: "{{ item }} needs to be set for the role to work"
    success_msg: "Required variable {{ item }} is defined"
  changed_when: false
  diff: false
  loop:
    - nsd_zone_vars.reverse_zone_name_v4
    - nsd_zone_vars.reverse_zone_name_v6
  when: nsd_zone_vars.reverse_zone_enabled is sameas true

- name: Verify that required DNSSEC zone attributes are defined
  ansible.builtin.assert:
    that:
      - "{{ item }} is defined"
      - "{{ item }} | length > 0"
      - "{{ item }} != None"
    fail_msg: "{{ item }} needs to be set for the role to work"
    success_msg: "Required variable {{ item }} is defined"
  changed_when: false
  diff: false
  loop:
    - nsd_zone_vars.dnssec_algo
    - nsd_zone_vars.zsk_rollover
    - nsd_zone_vars.zsk_grace_period
    - nsd_zone_vars.dnssec_propagation_delay
  when: nsd_zone_vars.dnssec_enabled is sameas true
