---
- name: Create nsd keys directory
  ansible.builtin.file:
    path: "{{ nsd_directory }}/keys"
    owner: root
    group: nsd
    state: directory
    mode: u=rwx,g=rx,o=x
  become: true

- name: Create nsd keys ZSK and KSK directories
  ansible.builtin.file:
    path: "{{ nsd_directory }}/keys/{{ item }}"
    owner: root
    group: nsd
    state: directory
    mode: u=rwx,g=rx,o=x
  loop:
    - ZSK
    - KSK
  become: true

- name: Create nsd zones directory
  ansible.builtin.file:
    path: "{{ nsd_directory }}/zones"
    owner: root
    group: nsd
    state: directory
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Create tmp, db and pidfile directory
  ansible.builtin.file:
    path: "{{ nsd_directory }}/{{ dir }}"
    owner: root
    group: nsd
    state: directory
    mode: u=rwx,g=rwx,o=rx
  become: true
  loop:
    - db
    - tmp
    - run
  loop_control:
    loop_var: dir
