- name: fetch all DKIM keys for the zonefile
  block:
    - name: read remote dkim key records {{ dkim_key.name }}
      command: "cat {{ '/etc/dkimkeys/' + postfix_mydomain + '/' + dkim_key.name + '.txt' }}"
      changed_when: false
      check_mode: false
      become: true
      register: dkim_cat

    - name: append key to list of dkim_keys
      set_fact:
        dkim_keys: "{{ dkim_keys | default([]) + [ dkim_cat.stdout ] }}"
