---
- name: Move environment file for systemd service
  ansible.builtin.template:
    src: zones/dnssecpls.env.j2
    dest: "{{ nsd_directory }}/{{ nsd_zone_name }}_dnssecpls.env"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true

- name: Update/create signed zone
  block:
    - name: Check if signed zone file is already present
      ansible.builtin.stat:
        path: "{{ nsd_server_zones_dir }}/{{ nsd_zone_name }}.zone.signed"
      become: true
      register: signed_zone

    - name: Update signed zone (when it exists)
      ansible.builtin.command: >
        {{ nsd_script_directory }}/dnssecpls
         --key_algo {{ nsd_dnssec_algo }}
         update_zone
         {{ nsd_zone_name }}
      args:
        chdir: "{{ nsd_directory }}"
      changed_when: true
      become: true
      when: signed_zone.stat.exists

    - name: Create signed zone (when it does not exists)
      ansible.builtin.command: >
        {{ nsd_script_directory }}/dnssecpls
         --key_algo {{ nsd_dnssec_algo }}
         create_zone
         --zsk_rotation_day {{ nsd_zsk_rotation_day }}
         --zsk_grace_period {{ nsd_zsk_grace_period }}
         --zsk_validity_period {{ nsd_zsk_validity_period }}
         {{ nsd_zone_name }}
      args:
        chdir: "{{ nsd_directory }}"
      changed_when: true
      become: true
      when: not signed_zone.stat.exists

  # TODO finish ksk_rotation day implementation
  # and add it to creation

- name: Make systemd services for zsk rollover of zone {{ nsd_zone_name }}
  block:
    - name: Move zskrollover systemd timer file to host
      ansible.builtin.template:
        src: systemd/zskrollover.timer.j2
        dest: "/etc/systemd/system/zskrollover@{{ nsd_zone_name }}.timer"
        # validate: "systemd-analyze verify %s"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      become: true

    - name: Move zskrollover.service systemd file to host
      ansible.builtin.template:
        src: systemd/zskrollover.service.j2
        dest: "/etc/systemd/system/zskrollover@{{ nsd_zone_name }}.service"
        # validate: "systemd-analyze verify %s"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      become: true

    - name: Validate zskrollover.service
      ansible.builtin.command: systemd-analyze verify zskrollover@{{ nsd_zone_name }}.service
      args:
        chdir: "/etc/systemd"
      changed_when: false
      become: true

    - name: Validate zskrollover.timer
      ansible.builtin.command: systemd-analyze verify zskrollover@{{ nsd_zone_name }}.timer
      args:
        chdir: "/etc/systemd"
      changed_when: false
      become: true

    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd:
        daemon_reload: true
      become: true

    - name: Enable zskrollover timer service
      ansible.builtin.service:
        name: zskrollover@{{ nsd_zone_name }}.timer
        state: started
        enabled: true
      become: true
# rest should be handled by zskrollover
