---
- name: Run serial script
  ansible.builtin.script:
    cmd: generate_serial.sh
  args:
    executable: /bin/bash
  changed_when: false
  check_mode: false
  delegate_to: localhost
  run_once: true
  register: generated_serial

- name: Set the generated serial as a fact
  ansible.builtin.set_fact:
    _generated_dns_serial: "{{ generated_serial.stdout | trim }}"
