# https://ubuntu.com/server/docs/service-domain-name-service-dns
# https://www.digitalocean.com/community/tutorials/how-to-configure-nsd-as-a-private-network-dns-server-on-debian-9
---
- name: Assert required variables for role are defined
  ansible.builtin.include_tasks:
    file: assert.yaml
    apply:
      delegate_to: localhost
      run_once: true
  tags:
    - nsd_assert

- name: install required packages
  ansible.builtin.package:
    name:
      - nsd
      - dnsutils
      - ldnsutils
      - python3-netaddr
    state: present
  become: true
  when: nsd_install
  tags:
    - nsd_install

- name: Create required directories
  ansible.builtin.include_tasks:
    file: create_directories.yaml
  tags:
    - nsd_setup

- name: check if certs are present
  ansible.builtin.stat:
    path: "{{ cert_file }}"
  become: true
  loop:
    - "{{ nsd_directory }}/nsd_server.key"
    - "{{ nsd_directory }}/nsd_server.pem"
    - "{{ nsd_directory }}/nsd_control.key"
    - "{{ nsd_directory }}/nsd_control.pem"
  loop_control:
    loop_var: cert_file
  register: control_certs
  tags:
    - nsd_setup

- name: setup nsd-control
  ansible.builtin.command: nsd-control-setup
  become: true
  # only run when not all certs are present
  when: "not control_certs.results | map(attribute='stat') | map(attribute='exists') | all"
  tags:
    - nsd_setup

- name: Move zone files to host
  include_tasks:
    file: move_zones.yaml
    apply:
      become: true
  loop: "{{ nsd_zone_attributes }}"
  loop_control:
    loop_var: nsd_zone_vars
  tags:
    - nsd_update

- name: Do DNSSEC for zones when required
  ansible.builtin.include_tasks:
    file: dnssec.yaml
  when: zone_vars.dnssec.enabled is true
  loop: "{{ nsd_zone_attributes }}"
  loop_control:
    loop_var: nsd_zone_vars
  tags:
    - nsd_update

- name: Move nsd.conf file template file to host
  ansible.builtin.template:
    src: conf.j2
    dest: "{{ nsd_directory }}/nsd.conf.d/nsd.conf"
    validate: "/usr/sbin/nsd-checkconf %s"
    owner: root
    group: root
    mode: u=rw,g=r
  become: true
  notify: restart nsd
  tags:
    - nsd_update
