---
- name: Rescope variables for readability
  block:
    - name: Rescope general variables
      ansible.builtin.set_fact:
        nsd_zone_name: "{{ nsd_zone_vars.name }}"
        nsd_ttl: "{{ nsd_zone_vars.ttl }}"
        nsd_dns_refresh: "{{ nsd_zone_vars.dns_refresh }}"
        nsd_dns_retry: "{{ nsd_zone_vars.dns_retry }}"
        nsd_dns_expire: "{{ nsd_zone_vars.dns_expire }}"
        nsd_dns_negative_response_cache: "{{ nsd_zone_vars.dns_negative_response_cache }}"
        nsd_make_ascii: "{{ nsd_zone_vars.make_ascii }}"
        nsd_dkim_enabled: "{{ nsd_zone_vars.dkim_enabled }}"
        nsd_dnssec_enabled: "{{ nsd_zone_vars.dnssec_enabled }}"
        nsd_reverse_zone_enabled: "{{ nsd_zone_vars.reverse_zone_enabled }}"

    - name: Rescope DKIM variables
      ansible.builtin.set_fact:
        nsd_dkim_domain: "{{ nsd_zone_vars.dkim_domain }}"
        nsd_dkim_keys: "{{ nsd_zone_vars.dkim_keys }}"
      when: nsd_dkim_enabled

    - name: Rescope DNSSEC variables
      ansible.builtin.set_fact:
        nsd_zsk_rollover: "{{ nsd_zone_vars.zsk_rollover }}"
        nsd_zsk_grace_period: "{{ nsd_zone_vars.zsk_grace_period }}"
        nsd_dnssec_propagation_delay: "{{ nsd_zone_vars.dnssec_propagation_delay }}"
        nsd_dnssec_algo: "{{ nsd_zone_vars.dnssec_algo }}"
      when: nsd_dnssec_enabled

    - name: Rescope reverse zone variables
      ansible.builtin.set_fact:
        nsd_reverse_zone_name_v4: "{{ nsd_zone_vars.reverse_zone_name_v4 }}"
        nsd_reverse_zone_name_v6: "{{ nsd_zone_vars.reverse_zone_name_v6 }}"
      when: nsd_reverse_zone_enabled

- name: Rescope records variable for readability
  ansible.builtin.set_fact:
    nsd_records: "{{ lookup('vars', 'nsd_' + nsd_zone_name | replace('.', '_') + '_records') }}"

- include_tasks: dkim_keys.yaml
  loop: "{{ nsd_dkim_keys }}"
  loop_control:
    loop_var: dkim_key
  tags:
    - nsd_update
  when: nsd_dkim_enabled

- name: move forward zone config file to host
  ansible.builtin.template:
    src: zone.j2
    dest: "{{ nsd_directory }}/zones/{{ nsd_zone_name }}.zone"
    validate: "/usr/sbin/nsd-checkzone {{ nsd_zone_name }} %s"
    owner: root
    group: nsd
    mode: u=rw,g=r,o=r
  notify: restart nsd

- name: move reverse zone v4 config file to host
  ansible.builtin.template:
    src: zone.rev4.j2
    dest: "{{ nsd_directory }}/zones/{{ nsd_reverse_zone_name_v4 }}.zone"
    validate: "/usr/sbin/nsd-checkzone {{ nsd_reverse_zone_name_v4 }} %s"
    owner: root
    group: nsd
    mode: u=rw,g=r,o=r
  when: nsd_reverse_zone_enabled
  notify: restart nsd

- name: move reverse zone v6 config file to host
  ansible.builtin.template:
    src: zone.rev6.j2
    dest: "{{ nsd_directory }}/zones/{{ nsd_reverse_zone_name_v6 }}.zone"
    validate: "/usr/sbin/nsd-checkzone {{ nsd_reverse_zone_name_v6 }} %s"
    owner: root
    group: nsd
    mode: u=rw,g=r,o=r
  when: nsd_reverse_zone_enabled
  notify: restart nsd

- name: Do DNSSEC for zones when required
  include_tasks:
    file: dnssec.yaml
  when: nsd_dnssec_enabled
